// Code generated by thriftrw-plugin-yarpc
// @generated

package history

import yarpcerrors "go.uber.org/yarpc/yarpcerrors"

// YARPCErrorCode returns a yarpcerrors.CodeAlreadyExists for EventAlreadyStartedError.
//
// This is derived from the rpc.code annotation on the Thrift exception.
func (e *EventAlreadyStartedError) YARPCErrorCode() *yarpcerrors.Code {
	code := yarpcerrors.CodeAlreadyExists
	return &code
}

// Name is the error name for EventAlreadyStartedError.
func (e *EventAlreadyStartedError) YARPCErrorName() string { return "EventAlreadyStartedError" }

// YARPCErrorCode returns a yarpcerrors.CodeAborted for ShardOwnershipLostError.
//
// This is derived from the rpc.code annotation on the Thrift exception.
func (e *ShardOwnershipLostError) YARPCErrorCode() *yarpcerrors.Code {
	code := yarpcerrors.CodeAborted
	return &code
}

// Name is the error name for ShardOwnershipLostError.
func (e *ShardOwnershipLostError) YARPCErrorName() string { return "ShardOwnershipLostError" }
