// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/cadence/common/quotas (interfaces: ICollection)
//
// Generated by this command:
//
//	mockgen -package=quotas -destination=collection_mock.go github.com/uber/cadence/common/quotas ICollection
//

// Package quotas is a generated GoMock package.
package quotas

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockICollection is a mock of ICollection interface.
type MockICollection[K comparable] struct {
	ctrl     *gomock.Controller
	recorder *MockICollectionMockRecorder[K]
	isgomock struct{}
}

// MockICollectionMockRecorder is the mock recorder for MockICollection.
type MockICollectionMockRecorder[K comparable] struct {
	mock *MockICollection[K]
}

// NewMockICollection creates a new mock instance.
func NewMockICollection[K comparable](ctrl *gomock.Controller) *MockICollection[K] {
	mock := &MockICollection[K]{ctrl: ctrl}
	mock.recorder = &MockICollectionMockRecorder[K]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICollection[K]) EXPECT() *MockICollectionMockRecorder[K] {
	return m.recorder
}

// For mocks base method.
func (m *MockICollection[K]) For(key K) Limiter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "For", key)
	ret0, _ := ret[0].(Limiter)
	return ret0
}

// For indicates an expected call of For.
func (mr *MockICollectionMockRecorder[K]) For(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "For", reflect.TypeOf((*MockICollection[K])(nil).For), key)
}
