// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/cadence/common/quotas (interfaces: LimiterFactory)
//
// Generated by this command:
//
//	mockgen -package=quotas -destination=limiterfactory_mock.go github.com/uber/cadence/common/quotas LimiterFactory
//

// Package quotas is a generated GoMock package.
package quotas

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLimiterFactory is a mock of LimiterFactory interface.
type MockLimiterFactory[K comparable] struct {
	ctrl     *gomock.Controller
	recorder *MockLimiterFactoryMockRecorder[K]
	isgomock struct{}
}

// MockLimiterFactoryMockRecorder is the mock recorder for MockLimiterFactory.
type MockLimiterFactoryMockRecorder[K comparable] struct {
	mock *MockLimiterFactory[K]
}

// NewMockLimiterFactory creates a new mock instance.
func NewMockLimiterFactory[K comparable](ctrl *gomock.Controller) *MockLimiterFactory[K] {
	mock := &MockLimiterFactory[K]{ctrl: ctrl}
	mock.recorder = &MockLimiterFactoryMockRecorder[K]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLimiterFactory[K]) EXPECT() *MockLimiterFactoryMockRecorder[K] {
	return m.recorder
}

// GetLimiter mocks base method.
func (m *MockLimiterFactory[K]) GetLimiter(key K) Limiter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLimiter", key)
	ret0, _ := ret[0].(Limiter)
	return ret0
}

// GetLimiter indicates an expected call of GetLimiter.
func (mr *MockLimiterFactoryMockRecorder[K]) GetLimiter(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLimiter", reflect.TypeOf((*MockLimiterFactory[K])(nil).GetLimiter), key)
}
